
        <div class="block feature-product">
            <div class="container" style="text-align: center;">
                <h2 class="h2-feat">FEATURED PRODUCTS</h2>
            <!-- Nav tabs -->
            <ul class="tabs">
                <li class="tab-link current" data-tab="tab-1"><span>Best seller</span></li>
                <li class="tab-link" data-tab="tab-2"><span>Top seller</span></li>
                <li class="tab-link" data-tab="tab-3"><span>Sale off</span></li>
            </ul>
            <!-- Tab panes -->
            </div>

            <div id="tab-1" class="tab-content current">
                <?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
                <div class="container widget widget-new-products">
                    <div class="widget-title">
                        <h2><?php echo $this->__('best-seller') ?></h2>
                    </div>
                    <div class="widget-products">
                        <?php echo $this->getPagerHtml() ?>
                        <?php $_columnCount = $this->getColumnCount(); ?>
                        <?php $i=0; ?>
                        <ul class="new-pro owl-carousel products-grid products-grid--max-<?php echo $_columnCount; ?>-col-widget">
                            <?php foreach ($_products->getItems() as $_product): ?>
                                <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                                    <?php $_imgSize = 262; ?>
                                    <?php // The image size is locked at 210 for this for display purposes. CSS has it at 75% which should equate to 278px?>
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
                                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(262,359) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
                                    </a>
                                    <div class="product-info">
                                        <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
                                        
                                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                        <?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
                                        <div class="actions">
                                            <ul class="add-to-links">
                                                <li><a href="#" class="link-wishlist">
                                                    <?php if ($_product->isSaleable()): ?>
                                                        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><i class="fa fa-shopping-bag" aria-hidden="true"></i></button>
                                                    <?php else: ?>
                                                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                                    <?php endif; ?>
                                                    </a>
                                                </li>
                                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                    <li><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><i class="fa fa-heart" aria-hidden="true"></i></a></li>
                                                <?php endif; ?>
                                                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                                    <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><i class="fa fa-pie-chart" aria-hidden="true"></i></a></li>
                                                    <li><a href="#" class="link-wishlist"><i class="fa fa-search-plus" aria-hidden="true"></i></a></li>
                                                <?php endif; ?>
                                            </ul>
                                        </div>
                                    </div>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
                <?php endif; ?>
            </div>
            <div id="tab-2" class="tab-content">
                <?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
                <div class="container widget widget-new-products">
                    <div class="widget-title">
                        <h2><?php echo $this->__('Top seller') ?></h2>
                    </div>
                    <div class="widget-products">
                        <?php echo $this->getPagerHtml() ?>
                        <?php $_columnCount = $this->getColumnCount(); ?>
                        <?php $i=0; ?>
                        <ul class="new-pro owl-carousel products-grid products-grid--max-<?php echo $_columnCount; ?>-col-widget">
                            <?php foreach ($_products->getItems() as $_product): ?>
                                <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                                    <?php $_imgSize = 262; ?>
                                    <?php // The image size is locked at 210 for this for display purposes. CSS has it at 75% which should equate to 278px?>
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
                                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(262,359) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
                                    </a>
                                    <div class="product-info">
                                        <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
                                        
                                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                        <?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
                                        <div class="actions">
                                            <ul class="add-to-links">
                                                <li><a href="#" class="link-wishlist">
                                                    <?php if ($_product->isSaleable()): ?>
                                                        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><i class="fa fa-shopping-bag" aria-hidden="true"></i></button>
                                                    <?php else: ?>
                                                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                                    <?php endif; ?>
                                                    </a>
                                                </li>
                                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                    <li><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><i class="fa fa-heart" aria-hidden="true"></i></a></li>
                                                <?php endif; ?>
                                                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                                    <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><i class="fa fa-pie-chart" aria-hidden="true"></i></a></li>
                                                    <li><a href="#" class="link-wishlist"><i class="fa fa-search-plus" aria-hidden="true"></i></a></li>
                                                <?php endif; ?>
                                            </ul>
                                        </div>
                                    </div>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
                <?php endif; ?>
            </div>
            <div id="tab-3" class="tab-content">
            </div>
        </div>
<script>
    jQuery(document).ready(function(){
        
        jQuery('ul.tabs li').click(function(){
            var tab_id = jQuery(this).attr('data-tab');

            jQuery('ul.tabs li').removeClass('current');
            jQuery('.tab-content').removeClass('current');

            jQuery(this).addClass('current');
            jQuery("#"+tab_id).addClass('current');
        })
    });
    jQuery('.new-pro.owl-carousel').owlCarousel({
        loop: true,
        navSpeed: 1000,
        smartSpeed:1000,
        margin: 20,
        // autoplay:true,
        nav:true,
        navText:['<a href="javascript:void(0)">prev</a>','<a href="javascript:void(0)">next</a>'],
        responsiveClass: false,
        responsive: {
            0: {
                items: 1,
                // autoplay:true,
                nav: true
            },
            568: {
                items: 2,
                // autoplay:true,
                nav: true
            },
            768: {
                items: 3,
                nav: true,
                loop: true,
                // autoplay:true,
                margin: 20
            },
            1024: {
                items: 4,
                nav: true,
                loop: true,
                // autoplay:true,
                margin: 20
            }               

        }
    });
</script>