
<div class="newsletter">
	<div class="container" >
		<div class="row">
			<div class="col-lg-6 col-md-6 left">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('cizero-newsletter')->toHtml() ?>
			</div>
			<div class="col-lg-6 col-md-6 right">
				<div class="block block-subscribe">
				    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
				        <div class="block-content">
				            <div class="input-box">
				               <input placeholder="<?php echo $this->__('Inserisci la tua e-mail') ?>" type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="newsletter" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Sign up for our newsletter')) ?>" class="input-text required-entry validate-email" />
				            </div>
					        <p class="policy">
					        	<input class="required-entry" name="policy" type="checkbox">
					        	<span>Ho letto e accetto la <ins>privacy policy</ins></a></span>
				        	</p>
				            <div class="actions">
				                <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Subscribe')) ?>" class="button"><span><span><?php echo $this->__('INVIA') ?></span></span></button>
				            </div>
				        </div>

				    </form>
				    <script type="text/javascript">
				    //<![CDATA[
				        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
				    //]]>
				    </script>
				</div>
			</div>
		</div>
	</div>
</div>
