<?php
/**
 * @author Liu Khang
 * @copyright Copyright (c) 2017
 * @package MessageSuscess_Lk
 */
?>
aaaaaaaaaaaaaaaaaaaaaaaa
<!-- Start -->
<button id="lk-myBtn">Open Modal</button>

<!-- The Modal -->
<div id="lk-myModal" class="lk-modal">

  <!-- Modal content -->
  <div class="lk-modal-content">
    <span class="lk-close">&times;</span>
    <?php echo $this->getChildHtml('global_messages') ?>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
  </div>

</div>

<script>
    // Get the modal
    var modal = document.getElementById('lk-myModal');

    // Get the button that opens the modal
    var btn = document.getElementById("lk-myBtn");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks on the button, open the modal 
    btn.onclick = function() {
      modal.style.display = "block";
    }

    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
      modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
      if (event.target == modal) {
        modal.style.display = "none";
      }
    }
    jQuery(document).ready(function(){
      if (jQuery("#lk-myModal .messages").html().length > 0) {
       jQuery('.lk-modal').show();
      }                                           
    });
  </script>
  <!-- End -->
</div>